---
- hosts: localhost
  collections:
    - ibm.ibm_zos_core_ftp
  gather_facts: no
  environment:
    FTP_USERID: "{{ FTP_USERID }}"
    FTP_PASSWORD: "{{ FTP_PASSWORD }}"
    FTP_HOST: "{{ FTP_HOST }}"
    FTP_JOB_CLASS: "{{ FTP_JOB_CLASS }}"
    FTP_JOB_MSGCLASS: "{{ FTP_JOB_MSGCLASS }}"
    FTP_SOCKS_PORT: "{{ FTP_SOCKS_PORT }}"

  tasks:
    - zos_operator:
        cmd: "{{ cmd }}"
      register: result
    - debug:
        msg: "{{ result }}"
    - set_fact:
        tmp_path: "/tmp/{{ cmd | replace(' ','_') }}.txt"
    - copy:
        content: "{{ '\n'.join(result.content) }}"
        dest: "{{ tmp_path }}"
      delegate_to: localhost
    - debug:
        msg: "{{ lookup('file', tmp_path).splitlines() }}"
